#%RAML 1.0
title: my-test-api
version: 1.0.0

protocols:
- HTTPS


traits:
  customerKeyRequired:
    headers:
      functionalId:
        type: avalaraCustomerLib.customerKey
        description: functionalId contains customerNumber, state, customerType will form customer key as json string
        example: !include example.raml


/hello:
  displayName: hello world.
  get:
  
      responses:
       200:
         body:
           application/json:        
            example: !include /example.raml


