#%RAML 1.0
title: my-test-api
version: 1.0.0

protocols:
- HTTPS

/hello:
  displayName: hello world.
  get:
      queryParameters:
        phoneNumber:
          type: string
          pattern: ^null|\+?$|\+?[0-9]{10}$
          required: false
          description: Phone Number of the Customer
          maxLength: 20
          example: null
        email:
          type: string
          required: false
          pattern: ^$|\+?.+@.+\..+$
          description: Email Id of the Customer
          maxLength: 50
          example: ""  
      description: Responds with hello world
      responses:
       200:
         body:
           application/json:        
            example: !include /example.raml


